
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://zkialbuorwxzebzzswww.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpraWFsYnVvcnd4emVienpzd3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDI4NTMsImV4cCI6MjA2MDA3ODg1M30.o0Rak7Gg4ZXu5EWMoueBPbp-P_mB-0j5c0-Ju-QXGO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
